# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_hypergeomPFQ <- function(m, a, b, x, alpha) {
    .Call('_HypergeoMat_Rcpp_hypergeomPFQ', PACKAGE = 'HypergeoMat', m, a, b, x, alpha)
}

